### ISSUE TITLE
 mini-Imagenet

### ISSUE THREAD

**Issue by zyqm123** [lovelyqian/StyleAdv-CDFSL#10]
I can not obtain  mini-Imagenet from this given link. Could you please give me thais dataset? Thank you very much.

**Comment by lovelyqian** [comment]
I will refer you to https://github.com/hushell/pmf_cvpr22/blob/main/scripts/download_miniimagenet.sh to download it.

**Comment by zyqm123** [comment]
Thank you very much! The issue is addressed now!
