### ISSUE TITLE
Can not reproduce the CUB results.

### ISSUE THREAD

**Issue by chenxiang3luo** [lovelyqian/StyleAdv-CDFSL#5]
Hi qian,
Thank you for your outstanding work. I want to reproduce the results on CUB with the weights provided by you, but I could not get good results reported in your paper. I only got 43.1%. The following are my testing codes used for extracting features. Are they proper?

![image](https://github.com/lovelyqian/StyleAdv-CDFSL/assets/80572402/800e35af-165b-4361-a2ce-a41fd49be23d)
![image](https://github.com/lovelyqian/StyleAdv-CDFSL/assets/80572402/75a150e2-5a67-4a99-a43b-eaf58bb69e0d)

**Comment by chenxiang3luo** [comment]
By the way, I used the following classifier.
![image](https://github.com/lovelyqian/StyleAdv-CDFSL/assets/80572402/a10c6c6b-4189-4e04-811e-a4f1faec20d2)

**Comment by lovelyqian** [comment]
> Hi qian, Thank you for your outstanding work. I want to reproduce the results on CUB with the weights provided by you, but I could not get good results reported in your paper. I only got 43.1%. The following are my testing codes used for extracting features. Are they proper?
> 
> ![image](https://private-user-images.githubusercontent.com/80572402/328178751-800e35af-165b-4361-a2ce-a41fd49be23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTkxNjAsIm5iZiI6MTcxNTE1ODg2MCwicGF0aCI6Ii84MDU3MjQwMi8zMjgxNzg3NTEtODAwZTM1YWYtMTY1Yi00MzYxLWEyY2UtYTQxZmQ0OWJlMjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NWE0YjMwODRmNjZlYzBiNDU2NjE1MTQ3Y2ZhNWRhYjYyMjdlMWFmZDM1ZWMzMmY0ZTk5YjIzOTUwOGQ1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pGTwyJ6j_MV0Ykm7lWV81vLqDhpAXK95FV_6YMfIIc) ![image](https://private-user-images.githubusercontent.com/80572402/328178884-75a150e2-5a67-4a99-a43b-eaf58bb69e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTkxNjAsIm5iZiI6MTcxNTE1ODg2MCwicGF0aCI6Ii84MDU3MjQwMi8zMjgxNzg4ODQtNzVhMTUwZTItNWE2Ny00YTk5LWE0M2ItZWFmNThiYjY5ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWRlNjFiMzAxZjZiOGUwNTM3NDRkZjNkZDg0MWRkNjQxZTJmYWUyNmM3OWU1ZGUxZDNlMzVkNTExMjhkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stsO0Tc_KHSssh2ooPdNq-OKF_sccwtIiK9YU4KmE0E)

Hi @chenxiang3luo , thanks for your question. The basic idea for extracting the feature looks proper, but the details e.g., dataset split, data processing, and classifier implemented by your code may be different.  How about directly using the code provided in this repo? I reproduce the results before releasing codes.  I think the result will be the same or at least very similar to our paper.

**Comment by chenxiang3luo** [comment]
> > Hi qian, Thank you for your outstanding work. I want to reproduce the results on CUB with the weights provided by you, but I could not get good results reported in your paper. I only got 43.1%. The following are my testing codes used for extracting features. Are they proper?
> > ![image](https://private-user-images.githubusercontent.com/80572402/328178751-800e35af-165b-4361-a2ce-a41fd49be23d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTkxNjAsIm5iZiI6MTcxNTE1ODg2MCwicGF0aCI6Ii84MDU3MjQwMi8zMjgxNzg3NTEtODAwZTM1YWYtMTY1Yi00MzYxLWEyY2UtYTQxZmQ0OWJlMjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NWE0YjMwODRmNjZlYzBiNDU2NjE1MTQ3Y2ZhNWRhYjYyMjdlMWFmZDM1ZWMzMmY0ZTk5YjIzOTUwOGQ1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pGTwyJ6j_MV0Ykm7lWV81vLqDhpAXK95FV_6YMfIIc) ![image](https://private-user-images.githubusercontent.com/80572402/328178884-75a150e2-5a67-4a99-a43b-eaf58bb69e0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTkxNjAsIm5iZiI6MTcxNTE1ODg2MCwicGF0aCI6Ii84MDU3MjQwMi8zMjgxNzg4ODQtNzVhMTUwZTItNWE2Ny00YTk5LWE0M2ItZWFmNThiYjY5ZTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWRlNjFiMzAxZjZiOGUwNTM3NDRkZjNkZDg0MWRkNjQxZTJmYWUyNmM3OWU1ZGUxZDNlMzVkNTExMjhkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stsO0Tc_KHSssh2ooPdNq-OKF_sccwtIiK9YU4KmE0E)
> 
> Hi @chenxiang3luo , thanks for your question. The basic idea for extracting the feature looks proper, but the details e.g., dataset split, data processing, and classifier implemented by your code may be different. How about directly using the code provided in this repo? I reproduce the results before releasing codes. I think the result will be the same or at least very similar to our paper.

okkk Thank you very much! I'll try it using the provided code.
